# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('device_category', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('www_authenticate', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('others', models.CharField(blank=True, max_length=200, null=True)),
                ('match_type', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'iie_banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'iie_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('model_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'iie_brand_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('category_cn_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_en_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('type_cn_name', models.CharField(blank=True, max_length=50, null=True)),
                ('type_en_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iie_device_type',
                'managed': False,
            },
        ),
    ]
