INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('4NSYS', '', '韩国', 'www.4nsys.com 监控产品的制造与供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('7Links', '', '德国', 'www.7links.me      IP Camera，路由器，NAS服务器，3G、4G、LTE网络服务', 'Monitor,Network Equipment,SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ABB', '', '瑞士', 'www.abb.com      工控领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ABUS', '安博', '德国', 'www.abus.com    安全产品制造商', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ACTi', '建腾创达', '中国台湾', 'www.acti.com      一个终端到终端的IP视频监控解决方案提供商，涵盖了所有的方式从安全到业务管理解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Advantech', '研华', '中国台湾', 'www.advantech.com     全球智能系统产业，提供全方面的软硬件、系统整合解决方案及专业设计制造服务，工控领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Aebell', '美电贝尔', '中国', 'www.aebell.com     专注于音视频算法核心技术及物联网智能感知技术的研发，是领先的智慧主动安防专业解决方案提供商，包括网络摄像机产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AipStar', '艾普视达', '中国', 'aipstar.cn    高清IP机芯模组OEM&ODM整体解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AirLink', '凌科', '中国', 'www.airlink-security.com    致力于提供出入口控制、闭路电视监控、侵入报警等电子安防系统的咨询和设计、系统集成、产品销售、培训和维护等服务', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AirLink101', '', '美国', 'airlink101.com      网络通信产品提供商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AirLive', '欧立', '中国台湾', 'www.airlive.com      OvisLink公司，网络、数据通信以及监控设备设备提供商', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AKCP', '', '美国', 'www.akcp.com      数据监控中心，物联网产品及方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Alarm', '', '美国', 'www.alarm.com     智能家居服务', 'HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Alibi', '', '美国', 'www.supercircuits.com  安全产品提供商', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Alien', '', '英国', 'www.aliendvr.com CCTV DVR供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Allen-Bradley', '艾伦-布拉德利', '美国', 'ab.rockwellautomation.com      提供优化性能所需的自动化组件和集成控制系统', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Allnet', '', '德国', 'www.allnet.de      网络和通信技术等诸多产品制造商，其中就有视频监控相关的摄像头', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Amcrest', '', '美国', 'amcrest.com    专业级安防监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Amegia', '', '中国台湾', 'www.asmag.com/amegia.co      开发和制造H.264百万像素网络摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Amovision', '', '美国', 'www.amovision.com       高清视频监控系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Android', '', '', '代表安卓设备', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Anjubao', '安居宝', '中国', 'www.anjubao.com      智能家居服务，其中视频监控系统当中就有相关摄像头设备', 'Monitor,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Anrine', '冠林', '中国', 'www.aurine.cn  楼宇对讲和智能家居产品研发制造商）', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Anybus', '', '瑞典', 'www.anybus.com      瑞典HMS公司的一个品牌，致力于是工业设备进行网络连接', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Appro', '', '中国台湾', 'www.approtech.com      IP视频监控设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Arecont Vision', '', '美国', 'www.arecontvision.com      IP百万像素技术领域的领军行业，致力于专业安防应用提供卓越的图像解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Armassa', '', '土耳其', 'www.armassa.com.tr 监控产品供应商', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Asoni', '新硕电通', '中国台湾', 'www.a-soni.com      在网络影像及CCTV安全监控产品上致力于发展\"网络安全监控解决方案\"，并提供网络影像管理及储存的软体服务', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Astak', '', '美国', 'www.astak.com      在安全和监控行业的领先的家庭和企业安全解决方案开发商，制造商和销售商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ASUS', '华硕', '中国台湾', 'www.asus.com.cn 先进的3C解决方案提供商。提供网络通信产品等', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Atlantis', '', '英国', 'www.atlantis-land.com      交换机、路由器、打印机、安全设备', 'Network Equipment,OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ATZ', '', '中国', 'www.atz-tech.com      出口专门对研发和设计的高品质和友好的智能家居产品，如智能IP可视门铃，网络摄像机，智能腕带，智能手表等。', 'Monitor,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AVer', '圆展', '中国台湾', 'tw.aver.com      高级视频监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Avigilon', '威智伦', '加拿大', 'avigilon.com      专注于设计、开发和制造视频分析、网络视频管理软件和硬件、监控摄像机以及门禁系统解决方案', 'Monitor,BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Avilink', '', '波兰', 'www.avilink.pl 波兰一家监控设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Aviosys', '', '中国台湾', 'www.aviosys.com      基于先进的网络电力远程访问管理解决方案，产品制造IP视频服务器，IP摄像机为全球广泛的市场和应用', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Avtech', '陞泰', '中国台湾', 'www.avtech.com.tw      CCTV制造商，提供全方位的监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('AXIS', '安迅士', '瑞典', 'www.axis.com     致力于网络监控视频方面，提供安防保护', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Axon', '', '荷兰', 'www.axon.tv      路由器，监控与控制', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('BEC', '', '美国', 'becintegrated.com 德克萨斯州理查森的电信设备供应商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Beck IPC', '', '德国', 'www.beck-ipc.com      Embedded Platform嵌入式系统和工业物联网', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Belkin', '贝尔金', '美国', 'www.belkin.com      美国一家监控摄像头提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('BeNext', '', '荷兰', 'www.benext.eu      其业务重点在家庭自动化市场，在气候，控制领域的中央控制点，能源，安全和安保，并提供了一个智能环境的最终用户', 'HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Beward', '', '俄罗斯', 'www.beward.ru  俄罗斯一家专业视频监控系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Biges', '', '土耳其', 'www.biges.com 土耳其一家专业级高清视频监控系统提供商，全球大概5万该供应商提供的视频监控系统暴露在互联网', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('BlueEyes', '蓝眼', '中国台湾', 'blueeyes.com.tw       一家科技公司教育培训产品和视讯监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('BlueSky', '蓝色星际', '中国', 'www.bstar.com.cn     视频监控、解决方案、监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Bosch', '博世', '德国', 'www.bosch.com      从事汽车与智能交通技术、工业技术、消费品和能源及建筑技术的产业', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Brickcom', '金砖通讯', '中国', 'www.brickcom.cn     开发并生产制造全系列数字安防监控系统产品，包括网络摄像机(Network Cameras)，影音伺服器(Video Servers)，影音解码器(Video Receiver)及综合网络数字监控平台(Video Management Software)，同时还提供齐全的配套数位产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Buffalo', '', '日本', 'buffalo.jp      是日本最大的电脑周边产品供应商，服务器、NVR、NAS', 'Monitor,SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('C-tech', '', '捷克斯洛伐克', 'mycam.c-tech.cz      摄像机、镜头', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Canon', '佳能', '日本', 'www.canon.com      以光学为核心的相机与办公设备制造商', 'Monitor,OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Cash2s', '', '法国', 'www.cash2s.com 安全系统供应商', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('CCTV', '', '', '一种技术不是一个品牌，大部分视频监控系统提供商都采用这种技术', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Cisco', '思科', '美国', 'www.cisco.com       网络通信产品、网络解决方案供应商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Clorius', '科罗里斯', '丹麦', 'www.cloriuscontrols.com   船舶控制器（控制系统）提供商，专门从事加热系统、冷却系统和通风系统的监测、控制和调节设备的开发和生产', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Cloud9', '', '印度', 'cloud9securities.in  CCTV设备制造商', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Cnaec', '克耐克', '中国', 'www.cnaec.net       楼宇对讲系统', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('CNB', '喜恩碧', '韩国', 'www.cnbtec.com        专业从事数字化安防监控系列产品的研发、生产及销售', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Commax', '科迈世', '韩国', 'www.commax.com      致力于楼宇可视对讲、智能家居领域的发展，是韩国最大的智能家居上市厂商', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ComOnyX', '', '俄罗斯', 'www.comonyx.com      一家监控设备系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Compro', '康博', '印度', 'www.comprousa.com 电脑显卡和多媒体设备    视频监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Conceptronic', '', '美国', 'www.conceptronic.com     视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Corega', '可瑞加', '日本', 'corega.jp 网络通信设备、视频监控设备供应商', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Coson', '科松电子', '中国', 'www.coson.com  致力于智能楼宇门禁、一卡通产品的开发、销售，安防工程项目的设计、安装及系统集成工作', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('CP Plus', '', '德国', 'www.cpplusworld.com CP PLUS是一家监控设备系统提供商主要产品包括DVR、HVR、NVR、IP Camera', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('CTC Union', '', '中国台湾', 'www.ctcu.com 致力于网络通讯产品的研发、制造与营销', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Cytech', '骏龙', '中国', 'www.cytech.com  电子组件分销商（分销公司）  监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('D-Link', '友讯', '中国台湾', 'www.dlink.com  专注于电脑网路设备（路由器）的设计开发', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Dahua', '大华', '中国', 'www.dahuatech.com 监控产品供应商和解决方案服务商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Das Intellitech', '达实智能', '中国', 'www.chn-das.com  致力于提供全生命周期的建筑机电节能解决方案，智能家居，智能楼宇，物联网解决方案', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('DD-WRT', '', '', '基于Linux的无线路由软件', 'Network Equipment,Wireless');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('DDS', '', '中国', 'www.dds.com.cn  安防产品制造商,主要生产先进的门禁控制和报警监测系统', 'BAS,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('DedicatedMicros', 'Dedicated Micros', '美国', 'dedicatedmicros.com  视频监控', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Dell', '戴尔', '美国', 'www.dell.com  为个人、家庭、企业办公等提供高品质戴尔产品及服务', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('DiViS ', '', '美国', 'divisdvr.com 领先的监控产品和系统制造商,特别专注于DVR', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('DynaColor', '彩富电子', '中国台湾', 'www.dynacolor.com.tw  致力于影像监控系统以及CRT/LCD自动监测系统', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Easycam', '', '', '一款屏幕录像软件', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ebode', '', '英国', 'www.ebodeelectronics.eu  提供行业领先的监控产品和系统解决方案。', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ecsino', '商智通', '中国', 'www.ecsino.com  互联网通讯与移动办公服务提供商', 'Network Equipment,OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Edimax', '迅舟', '中国', 'www.edimax.com.cn 无线网络通信设备创新生产厂家', 'Network Equipment,Wireless');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Elecom', '宜丽客', '日本', 'www.elecom.co.jp      生产制作网络通信产品', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Elphel', '', '美国', 'www3.elphel.com  提供高性能的摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Elster EnergyICT', '', '比利时', 'www.energyict.com 能源处理的公司，工控领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ENEO', 'eneo', '德国', 'eneo-security.com 提供视频监控安全的服务', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Epcom', '', '美国', 'www.epcom.net  无线和安全系统的分销商，包括视频监控，防盗系统等服务', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Epson', '爱普生', '日本', 'www.epson.com  致力于为客户提供数码影像创新技术和解决方案，打印机等产品', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Etrovision', '', '台湾', 'www.etrovision.com  设计与制造数字视频监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('EverFocus', '惠友', '中国台湾', 'www.everfocus.com  从事研发，制造，服务和闭路电视监控系统，CCD相机的全球营销和数字图像处理设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ExacqVision', '', '美国', 'www.exacq.com  VMS制造商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('FDT', '', '美国', 'fdt.us  无线网络摄像机制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Fine', '', '美国', 'www.finecctv.com  CCTV模拟摄像机，高速球型摄像机，硬盘录像机等网络设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Fitivision', '', '中国台湾', 'www.fitivision.com   OEM / ODM解决方案提供商，研发和大规模生产的IP摄像机和NVR', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('FLIR', '菲力尔', '美国', 'www.flir.com  红外热成像仪设计、制造及销售，工控领域设备产品', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Foscam', '福斯康姆', '中国', 'www.foscam.com.cn  智能网络摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('FUHO', '馥鸿', '中国', 'www.fuho.com.cn   CCTV 摄像机，数字硬盘录像机和周边器材供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Fuji Xerox', '富士施乐', '日本', 'www.fujixerox.com  数字与信息技术产品生产商，多媒体办公产品', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('GE', '通用电气', '中国', 'www.ge.com   提供技术和服务业务的跨国公司，各领域工控设备与系统', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('GeoVision', '奇偶科技', '中国台湾', 'www.geovision.com.tw  专注于数字安防监控系统的创新研发，以影像撷取、影像分析、影像压缩、影像处理等核心技术提供客戶智慧型应用及最佳经济效益的监控解決方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('GNET', '珍妮特', '韩国', 'www.gnetsystem.com 专业级高清视频监控系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Grain', '', '中国台湾', 'www.grain-media.com   视频监控系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Grandstream', '潮流网络', '美国', 'www.grandstream.com   主要产品包括：IP监控类：视频服务器、网络监控高速球、视频网络摄像机，IP通信类：网络电话终端、网络视频电话、语音网关、IP-PBX等。', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('GrandTec', '格兰达', '中国', 'www.grand-tec.com  专注和致力于提供机电一体化、自动化、智能化的解决方案和创新服务，工控领域设备', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('GST', '', '韩国', 'CCTV监控系统供应商', 'Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('H3C', '华三通信', '中国', 'www.h3c.com.cn   致力于IP技术与网络通信产品（交换机等设备）的研究、开发、生产、销售及服务', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HBGK', '汉邦高科', '中国', 'www.hbgk.net  安防产品及行业解决方案提供商，录像机、摄像头等产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HeroSpeed', '英雄速度', '美国', 'www.herospeed.net   10月25日新增，美国一家专业级高清视频监控系统提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hi Sharp', '昇锐', '中国台湾', 'www.hisharp.com.tw  专业视频和图像设计和制造商，提供视频监控相关产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hikvision', '海康威视', '中国', 'www.hikvision.com  安防监控产品及行业解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hilife', '', '印度', '无搜索结果', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HiSilicon', '海思', '中国', 'www.hisilicon.com   业务包括消费电子、通信等领域的芯片与模块解决方案', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Honeywell', '霍尼韦尔', '美国', 'www.honeywell.com   多元化高科技和制造企业，在全球，其业务涉及：航空产品和服务，楼宇、家庭和工业控制技术，汽车产品，涡轮增压器，以及特殊材料', 'ICS,BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hongshi', '红狮', '美国', 'www.redlion.net      红狮通过一个遍布全球的经销商渠道网络来销售工业自动化和网络化产品。', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hosafe', '豪仕', '中国', 'www.hosafe.com  10月2日新增  安全产品的制造商，产品系列：IP摄像机，CCTV摄像机，SDI摄像机，NVR（套件）和DVR（套件）', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HP', '惠普', '美国', 'www.hp.com  主要专注于打印机、数码影像、软件、计算机与资讯服务等业务', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HQ-Cam', '', '美国', 'hq-cam.com   监控产品的制造与供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('HuaWei', '华为', '中国', 'www.huawei.com 通信解决方案的供应商', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hunt', '', '美国', 'huntcctv.com  DVR,DSP Cameras等监控设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hybrex', '鼎翰', '中国台湾', 'hybrex.com  通信制造商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Hyking', '航景', '中国', 'www.kingcctv.com  一家从事安防监控产品研发、生产、销售一体的企业。提供专业的监控规划经验和建议，致力于环境监控设计整体解决方案。', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Iball', '', '印度', 'www.iball.co.in  路由器，CCTV，手机，电脑相关网络设备供应商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Illustra', '', '美国', 'www.illustracameras.com  开发IP Camera', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('IndigoVision', '英迪高', '英国', 'www.indigovision.com   做视频安全系统，视频监控安全管理，摄像机产品', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Infinova', '英飞拓', '美国', 'www.infinova.com.cn  研发、生产、销售电子安防与光通信设备', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ingersoll Rand', '英格索兰', '美国', 'company.ingersollrand.com  经营空气压缩设备,工具和电动工具等，工业电子产品', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Innorpo', '精华隆', '中国', 'www.innopro.cc 精专安防行业的防盗报警产业，智能家居等', 'HA,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Insteon', '', '美国', 'www.insteon.com', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Intelbras', '', '巴西', 'www.intelbras.com.br   程控交换机、电话机、无线电话、传真机、对讲机、手机、网络产品、安防产品', 'BAS,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Intellinet', '', '美国', 'www.intellinet-network.com  网络产品供应商，包括摄像机、交换机等', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('IQinVision', '', '美国', '高清监控摄像头制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('IZON', '', '美国', 'www.izoncam.com     IZON IP Camera是美国Stem Innovation公司的网络摄像机产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('JFL', '', '巴西', 'www.jfl.com.br  监控设备制造商主要产品包括DVR、HVR、NVR、IP Camera', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Jiale', '佳乐', '中国', 'www.jiale.com  智能家居和楼宇安防产品的提供商', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Jovision', '中维世纪', '中国', 'www.jovision.com   高清网络摄像机、网络硬盘录像机、智能安防监控系统等基于云视通的全系列音视频技术与服务提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Joyware', '中威电子', '中国', 'joyware.com  高清安防监控产品解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('JSST', '捷顺', '中国', 'www.jieshun.cn   主营业务为各种出入口控制与管理产品的研发、生产、销售和服务，物联网解决方案，智能管理平台，包括视频监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('JXJ', '佳信捷', '中国', 'www.szjxj.com 视联网整体解决方案提供商及运营商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('JYD', '竞业达', '中国', 'www.jyd.com   竞业达是多媒体教学行业的领航者和国内著名的信息系统集成商，并在考试、市政、法院、交通、部队等行业信息化办公领域取得长足发展', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Kaicong', '凯聪', '中国', 'www.kaicong.net  研发生产销售安装各种监控摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Karassn', '科立信', '中国', 'www.karassn.com 各类安防设备供应商，包括网络摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Kedacom', '科达', '中国', 'www.kedacom.com  视频监控、视讯与安防产品及解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Keebox', '', '美国', 'www.keebox.com  KEEBOX是一家加利福尼亚州公司，由业内资深人士创办，目标是以合理的价格提供最优质的网络产品，包括摄像机、交换机等', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Keeper', '', '中国', 'www.keeper.cn 专业CCTV系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('KGuard', '', '中国台湾', 'www.kguardsecurity.com 全球知名安全监控产品专业制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Kocom', '科高姆', '韩国', 'www.kocom.com  智能家居系统和楼宇自动化系统', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Konica Minolta', '柯尼卡美能达', '日本', 'www.konicaminolta.com  经营办公设备业务', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Konlan', '康联', '中国', 'www.konlan.cn  智能云接警平台、报警运营服务、防盗报警、视频监控、GPS车辆管理系统等产品的研发、生产、销售、安装、维护等', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Kotikamera', '', '芬兰', 'verkkokauppa.kotihalytin.fi  智能家居服务', 'HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Kyocera', '京瓷', '日本', 'www.kyocera.com   跨越多个领域,提供先进的产品和服务，包括办公信息设备', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Leelen', '立林科技', '中国', 'www.leelen.com 社区安防系统设备供应商，智能家居、智能楼宇', 'BAS,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('LevelOne', '', '德国', 'global.level1.com  提供个人及企业高品质的网络通信与视频监控产品和解決方案', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Lexmark', '利盟', '美国', 'www.Lexmark.com  激光打印机的开发及生产商', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('LG', '乐金', '韩国', 'lg.net/main/main.dev  全称乐喜金星 是韩国LG集团中文名称 英文称为LUCKY GOLDSTAR，事业领域覆盖化学能源、电子电器、安防系统等领域', '*');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Lilin', '利凌', '中国台湾', 'www.meritlilin.com  提供网络监控完整解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Linhof', '', '英国', 'linhof.com  监控设备制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Linksys', '领势', '美国', 'www.linksys.com  路由器等产品品牌', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('LogiLink', '', '德国', 'www.logilink.eu   综合布线和通信应用方面高质量产品的厂商', 'Network Equipment,Room Wiring');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('LonBon', '来邦科技', '中国', 'lonbon.corp.dav01.com  从事“来邦对讲”系列产品的开发、生产及销售,来邦致力于IP网络产品的研发', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Longse', '长视', '中国', 'www.longse.cn 安防设备厂商，是目前中国大陆最大的监控设备生产厂家之一', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Lorex', '', '美国', 'www.lorextechnology.com  安全解决方案提供商，网络视频监控设备及平台', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('LTS', '', '美国', 'www.ltsecurityinc.com  网络设备供应商，包括视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Luma', '', '美国', 'www.lumasurveillance.com 安全解决方案提供商，网络视频监控设备及平台', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('M@cro-Video', '宏视', '中国', 'www.macro-video.com  视频监控设备、安全防范系统软、硬件研发、制造、 销售', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('MARCH', '', '加拿大', 'www.marchnetworks.com 提供行业领先的监控产品和系统解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Marshall', '', '美国', 'www.mars-cam.com 网络设备供应商，包括视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Matrix', '', '美国', 'www.matrixsecusol.com    安全产品解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('MayGion', '', '', '视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Mediatrix', '', '加拿大', 'www.media5corp.com 网络设备供应商', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Megapixel', '智赛电子', '中国', 'www.megapixel.com.cn  从事摄像机光学镜头的研发、生产、销售与服务于一体的企业', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Messoa', '', '中国台湾', 'www.messoa.com 视频监控系统供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Microdigital', '', '韩国', 'www.microdigital.co.kr  视频监控设备制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Micronet', '微网', '台湾', 'www.micronet.com.tw  提供全方位的存储解决方案）', 'SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Milestone', '麦视通', '丹麦', 'www.bestcontrol.com.cn  研究、设计、开发并提供IP视频监控与管理软件解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Minking', '明景电子', '中国', 'www.minkingcctv.com  摄像机，研制,开发,生产闭路电视监控设备的制造企业', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Mitsubishi', '三菱', '日本', 'cn.mitsubishielectric  电子和电气产品制造商，工业自动化产品', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Mobotix', '', '德国', 'www.mobotix.org.cn  网络摄像机厂商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Moxa', '摩莎', '中国台湾', 'www.moxa.com  提供工业联网、工业计算和远程自动化解决方案', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('MSV', '', '美国', 'www.mysmartvideo.com 设计制造的电子安全系统   网络摄像机产品', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('MVPower', '', '美国', 'www.mvpower.us  视频监控系统供应商主要产品包括DVR、NVR、IP Camera,采用HD CCTV 技术', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('N-CITY', '', '中国台湾', 'www.n-city.com.tw   网络设备供销商     网络摄像头产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NEO Coolcam', '丽欧酷视', '中国', 'cn.szneo.com  摄像头产品研发、生产、营销于一体的企业', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NeoVizus', '', '俄罗斯', 'videoglaz.ru  批发和零售的安全设备，包括摄像头产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NetCam360', '', '', 'www.netcam360.com 网络摄像机应用工具', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Netgear', '', '美国', 'www.netgear.com  企业网络解决方案，及数字家庭网络应用   路由器、交换机、存储服务器等产品', 'Network Equipment,SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NetSafe', '', '新西兰', 'www.netsafe.org.nz  提供网络互连安全服务   网络安全', 'Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Netwave', '', '英国', 'www.netwave.eu  提供和netwave技术相关的服务  包括摄像头产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NetZeye', '', '美国', 'www.netzeye.com  监控设备供销商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NG', 'NG Systems', '英国', 'www.ngsystems.co.uk 设计监控系统解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Nordex', '', '德国', 'www.nordex-online.com 风力涡轮机制造商，工业领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Novus', '', '波兰', 'www.novuscctv.com  CCTV视频监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('NRG', '', '美国', 'www.nrg.com  工业电力能源公司', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Nuuo', '京晨科技', '中国台湾', 'www.nuuo.com  视频监控解决方案供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('OKI', '日冲电气', '日本', 'www.okidata.com  研究、生产和销售打印机与传真机等', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Omron', '欧姆龙', '日本', 'www.omron.com  自动化控制及电子设备制造厂商', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Onsee', '天视达', '中国', 'www.onsee.net.cn 无线网络摄像机、POE网络摄像机、光纤网络摄像机、红外智能网络摄像机、防爆型网络摄像机、高清网络摄像机等产品专业生产加工', 'Monitor,Wireless');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Panasonic', '松下', '日本', 'www.panasonic.com  各类电器电子产品，包括摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Peake', '披克电子', '中国', 'www.peake.com.cn  非接触式IC卡应用产品专业生产商和一卡通系统解决方案提供商，物联网智能出入，包括智能门禁等', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Pearmain', '红苹果', '中国', 'www.pearmain-cctv.net  监控产品供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Pelco', '派尔高', '美国', 'www.pelco.com  研发和生产视频监控安保系统', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('PhyLink', '', '美国', 'www.phylink.com  研发，生产和销售视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('PiXORD', '', '中国台湾', 'www.pixord.com 提供鱼眼网络摄像机，智能家居网络摄像机，百万像素网络摄像机，长距离以太网扩展，VDSL2解决方案', 'Monitor,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Planet', '', '中国台湾', 'www.planet.com.tw  网络通讯产品的研发与行销', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Planex', '', '日本', 'www.planex.co.jp  销售网卡，路由器，交换机，L3网管型交换机，配件，蓝牙产品，打印服务器，苹果周边产品、网络存储设备等', 'Network Equipment,SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Polycom', '宝利通', '美国', 'www.polycom.com  提供端到端语音、视频、数据和 Web 富媒体协作应用的跨国企业（语音协作、视频协作）', 'Voice and Video');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Pravis', '', '韩国', 'www.pravis.co.kr  视频监控系统解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Proline', '', '英国', 'prolineuk.com  视频监控安防设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Provision-ISR', '', '以色列', 'www.provision-isr.com  CCTV视频监控产品制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Proximity', '', '黎巴嫩', 'proximity-lb.com/proximity/products/fine-cctv/ip-camera/    视频监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Q-See', '', '美国', 'q-see.com  智能安防监控品牌', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('QNAP', '', '台湾', 'www.qnapsecurity.com 领先的监控产品和系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('QTECH', '', '俄罗斯', 'www.qtechglobal.com  摄像头模组制造商', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('RaySharp', '安联锐视', '中国', 'www.raysharp.cn 专业的安防视频监控解决方案提供商', '');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Red Lion', '红狮', '美国', 'www.redlion.net       专业工业控制产品提供商', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Reliance', '瑞恩电气', '印度', 'www.ril.com   经营范围包括石化产品、合成纤维、纤维中间体、纺织品、石油和天然气、精炼和销售、电力、电信和信息产业、金融服务和保险等。', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ricoh', '理光', '日本', 'www.ricoh.com 办公设备及光学机器制造商', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Rifatron', '', '韩国', 'www.rifatron.com 视频监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Rockwell', '罗克韦尔', '美国', 'www.rockwellautomation.com  致力于工业自动化与信息', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Rosewill', '罗维', '美国', 'www.rosewill.com  以生产销售电脑周边类产品为主要业务 包括路由器，无线路由器，无线AP等', 'Network Equipment,Wireless');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('RTS Services', '', '德国', 'www.rts-services.de 维修，技术服务，电子硬件和复杂的仓储和物流解决方案的处理，工控方面', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ruckus', '', '美国', 'www.ruckuswireless.com 网络设备制造商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('RVi', '', '俄罗斯', 'www.rvi-cctv.ru  监控系统解决方案以及设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Samson', '萨姆森', '德国', 'www.samson.de  控制阀及自动控制设备专业制造商', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Samsung', '三星', '韩国', 'www.samsung.com 业务涉及电子、金融、机械、化学等众多领域，生产摄像头设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Santachi', '金三立', '中国', 'www.santachi.com.cn  集研发、生产、销售、服务为一体的视频监控设备整体制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sanyo', '三洋', '日本', 'www.sanyo.com 产品涉及显示器、手机、数码相机、机械、生物制药等众多领域，包括工控产品、视频监控产品', 'Monitor,ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Schleifenbauer', '', '荷兰', 'schleifenbauer.eu PDU制造商', 'Room Wiring');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Schneider', '施耐德', '法国', 'www.schneider-electric.com   工控自动化，在数据中心和网络、楼宇、工业、能源及基础设施等领域提供产品和解决方案', 'ICS,BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Secom', '西科姆', '英国', 'www.secom.plc.uk  提供安全产品解决方案', 'Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SecurVision', '', '德国', 'www.securvision.info 监控设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sentry360', '', '美国', 'sentry360.com  百万像素监控摄像机和视频管理软件制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sercomm', '中怡数宽', '中国', 'www.sercomm.com  致力于网通软、硬件产品整合服务与网络协议(IP Protocol) 等核心技术之研发，网络通信设备、无线宽带设备厂商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Shany', '', '中国台湾', 'www.shany.com  致力于监测和监视设备的设计和制造', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sharp', '夏普', '日本', 'www.sharp.cn 日本电子产品制造商，个人及家用产品，电脑办公、多媒体设备', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Shidean legrand', '视得安罗格朗', '中国', 'www.legrand.com.cn  智能家居', 'HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Shimano', '禧玛诺', '日本', 'www.shimano.com  运动摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Siemens', '西门子', '德国', 'www.siemens.com  工控、安防监控', 'Monitor,ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SMA Sunny', '', '德国', 'www.sma.de 工业领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SMAX', '', '中国台湾', 'www.smax.com.tw  摄像头产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SMC', '', '美国', 'na.smc.com 提供视频监控服务以及SMC网络物联网传感器，IP Camera等设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SoftPLC', '', '德国', 'www.softplc.com   工业软件解决方案提供商', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sony', '索尼', '日本', 'www.sony.com  涉及视听、电子游戏、通讯产品和信息技术等领域', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('SpiderControl', '', '德国', 'spidercontrol.net 工业自动化领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('StartVision ', '', '中国', 'www.startvision.cn 专业CCTV系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Storex', '', '法国', 'storex.fr  相机，平板电脑，摄像头等网络产品供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Stulz', '世图兹', '德国', 'www.stulz.com  空调公司，工业制造领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sunell', '景阳', '中国', 'www.sunell.com.cn  专注于高清摄像机、高速球、迷你型红外球机、热成像、全景摄像机、NVR及智能楼宇系统、森林防火、智慧城市解决方案的技术研发及市场服务', 'Monitor,BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Sunluxy', '', '德国', 'www.sunluxy.com', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Surveon', '', '中国台湾', 'www.surveon.com  视频监控设备供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Swann', '', '美国', 'www.swann.com  美国安防监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Synology', '群晖科技', '中国台湾', 'www.synology.com  为家庭与企业用户提供 RAID 存储、虚拟化存储、备份、视频监控与移动应用程序等支持', 'Monitor,SAN');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Syntell', '', '加拿大', 'www.syntell.com  商务智能解决方案提供商，包含摄像头产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Syscom', '凌群电脑', '中国', 'www.syscom.com.cn  提供包括主机、监控、网路、周边、应用系统与各项专业服务', 'Monitor,Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Systec', '', '韩国', 'salesystec.en.ec21.com       视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Systemmax', '', '埃及', 'system-max.com  零售及IT服务企业，包括IP摄像机等产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Taiji', '太极', '中国', 'www.taiji.com.cn  以咨询服务、行业解决方案服务、基础设施服务、运营服务等为主营业务，信息安全、ERP等产品', 'OA,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tamron', '腾龙光学', '日本', 'www.tamron.com.cn  一家以技术为资本的综合性专业光学摄像机镜头制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tandberg', '泰德', '美国', 'www.tandbergdata.com  视频会议系统制造商', 'Voice and Video');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tantos', '', '俄罗斯', 'tantos.pro 产品有网络视频监控，防盗报警系统等', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Techno vision', '', '印度', 'www.technovisioncctv.com 领先的CCTV系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Telege', '普天天纪', '中国', 'www.telege.cn  楼宇智能有限公司', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tenvis', '', '中国', 'www.tenvis.com 专业CCTV系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TI', '德州仪器', '美国', 'www.ti.com  德州仪器以开发、制造、销售半导体和计算机技术闻名于世，主要从事数字信号处理与模拟电路方面的研究、制造和销售，包括有监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tiandy', '天地伟业', '中国', 'www.tiandy.com  一家安防监控产品研发、生产、营销为主营业务的物联网企业', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Toshiba', '东芝', '日本', 'www.toshiba.com   数字技术、移动通信技术和网络技术等领域', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Totolink', '盛世众唐', '中国', 'www.totolink.cn   路由器', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TP-Link', '普联', '中国', 'www.tp-link.com.cn  网络通讯设备供应商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Trend', '霍尼韦尔卓灵', '英国', 'www.honeywell.com 楼宇自控系统', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TrendNet', '趋势网络', '美国', 'www.trendnet.com  数据网络专业厂商，提供视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tridium', '', '美国', 'www.tridium.com  一个集研究控制系统体系架构、开发相关应用软件和提供管理服务为一体的公司', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TruVision', '', '美国', 'www.interlogix.com  nterlogix公司的一个摄像机品牌', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TS Microtech', '', '美国', 'www.netzeye.com 包括有摄像头等设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('TVT', '同为数码', '中国', 'www.tvt.net.cn  一家集研发、生产、销售、服务于一体的视频监控专业制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Tyco', '泰科', '美国', 'www.tyco.com  电气、电子元件制造商和服务商；海底通信系统的设计、生产、安装和服务商；防火系统和电子安全服务的生产商、安装商和供应商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Ubiquiti', '优比快', '美国', 'www.ubnt.com  无线网络产品提供及方案解决', 'Wireless');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Unimo', '', '日本', 'unimo.com.au  日本安防监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Uniview', '宇视', '中国', 'cn.uniview.com  专业视频监控产品及解决方案供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Vbrick', '', '美国', 'vbrick.com  提供视频监控解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Verint', '惠锐', '美国', 'www.verint.com  IP摄像机视频解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Vicon', '威廉', '美国', 'www.vicon-security.com  安全产品提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Videcon', '', '英国', 'www.videcon.co.uk 监控产品供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('VideoTeknika', '', '意大利', 'videoteknika.com  视频监控设备以及解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('VideoVigilancia', '', '西班牙', 'www.videovigilancia.com  视频监控设备提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Videovox', '', '俄罗斯', 'www.videovox.ru  提供与汽车相关的电子产品    视频设备DVR等', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Viessmann', '菲斯曼', '德国', 'www.viessmann.cn  菲斯曼集团是世界领先的供热、制冷和空调系统制造商之一。工业领域', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Vikvision', '维康微视', '中国', 'www.hikvision.com  安防产品及行业解决方案提供商  主要生产视频监控产品', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Vimicro', '中星电子', '中国', 'www.vimicro.com.cn  电脑、宽带、移动通讯', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Visual Tools', '', '西班牙', 'www.visual-tools.com 领先的监控产品和系统制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Vivotek', '晶睿', '中国台湾', 'www.vivotek.com  网络视频监控解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('VMAX', '', '美国', 'digital-watchdog.com 专业视频监控产品供应商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Voltek', '', '英国', 'www.voltek.co.uk  设计和制造的电子安防产品   CCTV摄像机', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('VStarcam', '威视达康', '中国', 'www.vstarcam.cn 智能家居 平安e家 网络摄像机 Baby Monitor等', 'Monitor,HA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('WAGO', '万可', '德国', 'global.wago.com  涉及电气连接领域，工业', 'ICS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Wanjiaan', '万家安', '中国', 'www.relong.net  主要经营视频技术及视频监控安防解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Woshida', '沃仕达', '中国', 'www.woshida.com.cn  从事安防监控系列产品的研发、生产、销售为一体的新兴高科技企业', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('XiongMai', '雄迈', '中国', 'www.xiongmaitech.com  视频监控设备模组提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Y-cam', '天敏', '英国', 'www.y-cam.com  监控视频系统解决方案提供商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('YAAN', '亚安', '中国', 'www.chinayaan.com  致力于为社会提供高品质的安防及电视监控产品、技术和服务', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('YOKO', '悠克电子', '中国台湾', 'www.yoko-tech.com  监控摄影机制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Yudor', '', '中国台湾', 'www.yudor.com.tw    致力于开发安全系统，并提供创新的总监控解决方案，生产网络摄像机，NVR（网络视频录像机）和智能软件', 'Monitor,Security');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Zavio', '翰禹', '中国台湾', 'www.zavio.com  网络摄像机制造商', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Zebra', '斑马', '美国', 'www.zebra.com  网络办公设备以及解决方案提供商', 'OA');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Zero-One', '', '加拿大', 'www.zerooneinc.com     包含视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ZKSoftware', '中控科技', '中国', 'www.zksoftware.com 提供中控智慧考勤机,北京考勤机,中控智慧门禁安装,指纹考勤机', 'BAS');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('Zmodo', '智美达', '中国', 'www.zmodo.com.cn 智能互联网设备、解决方案与平台的提供商  包括视频监控设备', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ZNV', '中兴力维', '中国', 'www.znv.com.cn  提供行业领先的监控产品和系统解决方案', 'Monitor');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ZTE', '中兴', '中国', 'www.zte.com.cn  综合通信解决方案提供商', 'Network Equipment');
INSERT INTO `iie_brand`(en_name, cn_name, country, description, product_type) VALUES ('ZyXEL', '和勤科技', '美国', 'www.zyxel.com  提供网络服务', '*');
